/** TS consumer output: row interfaces + static-query manifest. TS resources
 *  register the manifest with the core resource and call execute(queryId,
 *  params) — same boundary discipline as every other language. */
import type { CodegenSchema } from './schema-model';
import { tsTypeOf } from './type-maps';

const pascal = (s: string) => s.replace(/(?:^|_)([a-z])/g, (_, c: string) => c.toUpperCase());

export function emitTs(schema: CodegenSchema): string {
  const out: string[] = ['// generated by hyper-db codegen — do not edit', ''];

  for (const table of schema.tables) {
    out.push(`export interface ${pascal(table.name)}Row {`);
    for (const [name, col] of Object.entries(table.columns)) {
      const optional = col.notNull ? '' : ' | null';
      out.push(`  ${name}: ${tsTypeOf(col.sqlType)}${optional};`);
    }
    out.push('}', '');
  }

  out.push('export const queries = {');
  for (const q of schema.queries) {
    out.push(`  ${q.name}: {`);
    out.push(`    queryId: ${JSON.stringify(q.queryId)},`);
    out.push(`    sql: ${JSON.stringify(q.sql)},`);
    out.push(`    paramCount: ${q.paramCount},`);
    out.push(`    table: ${JSON.stringify(q.table)},`);
    out.push('  },');
  }
  out.push('} as const;', '');
  return out.join('\n');
}
