/** Lua consumer output: EmmyLua (lua-language-server) annotated repo modules.
 *  Static queries call HyperDb.execute(queryId, params); dynamic chains build
 *  a flat descriptor via the client-lua runtime — both cross the boundary as
 *  scalar string + flat array only. */
import type { CodegenSchema } from './schema-model';
import { luaTypeOf } from './type-maps';

const pascal = (s: string) => s.replace(/(?:^|_)([a-z])/g, (_, c: string) => c.toUpperCase());

export function emitLua(schema: CodegenSchema): string {
  const out: string[] = [
    '-- generated by hyper-db codegen — do not edit',
    "-- requires the client-lua runtime (hyperdb.lua) loaded as 'HyperDb'",
    '',
  ];

  for (const table of schema.tables) {
    const className = pascal(table.name);
    out.push(`---@class ${className}Row`);
    for (const [name, col] of Object.entries(table.columns)) {
      const type = luaTypeOf(col.sqlType) + (col.notNull ? '' : '|nil');
      out.push(`---@field ${name} ${type}`);
    }
    out.push('');
    out.push(`${className} = {}`);
    out.push('');
    out.push(`--- Start a typed query chain on ${table.name}.`);
    out.push(`---@param col string`);
    out.push(`---@param op '=='|'~='|'>'|'>='|'<'|'<='|'like'`);
    out.push(`---@param value any`);
    out.push(`---@return HyperDbChain`);
    out.push(`function ${className}.where(col, op, value)`);
    out.push(`  return HyperDb.chain('${table.name}'):where(col, op, value)`);
    out.push('end');
    out.push('');
    out.push(`---@return HyperDbChain`);
    out.push(`function ${className}.query()`);
    out.push(`  return HyperDb.chain('${table.name}')`);
    out.push('end');
    out.push('');
  }

  for (const q of schema.queries) {
    const className = pascal(q.table);
    const args = Array.from({ length: q.paramCount }, (_, i) => `p${i + 1}`);
    out.push(`--- static query (${q.sql})`);
    for (const a of args) out.push(`---@param ${a} any`);
    out.push(`---@param cb? fun(rows: ${className}Row[])`);
    out.push(`---@return HyperDbPending`);
    out.push(`function ${className}.${q.name}(${[...args, 'cb'].join(', ')})`);
    out.push(`  return HyperDb.execute('${q.queryId}', { ${args.join(', ')} }, cb)`);
    out.push('end');
    out.push('');
  }

  return out.join('\n');
}
