/** C# (Mono v2) consumer output: DTOs + column descriptors + generated method
 *  chains (no LINQ expression trees — predictable, fast). Executes through the
 *  isolated HyperDb runtime; every C# consumer must keep a Lua/TS fallback
 *  path per the PRD risk rule. */
import type { CodegenSchema } from './schema-model';
import { csTypeOf } from './type-maps';

const pascal = (s: string) => s.replace(/(?:^|_)([a-z])/g, (_, c: string) => c.toUpperCase());

export function emitCs(schema: CodegenSchema): string {
  const out: string[] = [
    '// generated by hyper-db codegen — do not edit',
    'using System.Collections.Generic;',
    'using HyperDb.Runtime;',
    '',
    'namespace HyperDb.Generated',
    '{',
  ];

  for (const table of schema.tables) {
    const className = pascal(table.name);
    out.push(`    public sealed class ${className}Row`);
    out.push('    {');
    for (const [name, col] of Object.entries(table.columns)) {
      out.push(`        public ${csTypeOf(col.sqlType, col.notNull)} ${pascal(name)} { get; set; }`);
    }
    out.push('    }');
    out.push('');
    out.push(`    public static class ${className}`);
    out.push('    {');
    for (const name of Object.keys(table.columns)) {
      out.push(`        public static readonly Column ${pascal(name)} = new Column("${name}");`);
    }
    out.push('');
    out.push(`        public static QueryChain<${className}Row> Where(ColumnFilter filter)`);
    out.push(`            => new QueryChain<${className}Row>("${table.name}").Where(filter);`);
    out.push('');
    out.push(`        public static QueryChain<${className}Row> Query()`);
    out.push(`            => new QueryChain<${className}Row>("${table.name}");`);

    const tableQueries = schema.queries.filter((q) => q.table === table.name);
    for (const q of tableQueries) {
      const args = Array.from({ length: q.paramCount }, (_, i) => `object p${i + 1}`);
      const argNames = Array.from({ length: q.paramCount }, (_, i) => `p${i + 1}`);
      out.push('');
      out.push(`        // static query (${q.sql})`);
      out.push(`        public static Coroutine<List<${className}Row>> ${pascal(q.name)}(${args.join(', ')})`);
      out.push(`            => Db.Execute<${className}Row>("${q.queryId}", new object[] { ${argNames.join(', ')} });`);
    }
    out.push('    }');
    out.push('');
  }

  out.push('}');
  out.push('');
  return out.join('\n');
}
